# L'informazione mancante, fra "fake" e dashboard. L'iniziativa della Regione Abruzzo {#tollis}

Antonella Tollis

::: {.bio}
Giornalista, responsabile Ufficio informazione e social media della Regione Abruzzo, coordinatrice regionale di PaSocial (antonella.tollis\@regione.abruzzo.it).
:::

Tentare di analizzare la complessità dei fenomeni correlati al Covid-19, nel momento in cui si appropria letteralmente delle nostre vite, è complicato. Per i limiti connessi alla contemporaneità dei fatti, all'emergenza e alle posizioni strumentali delle varie parti in campo. L'analisi è tuttavia utile a conservare viva l'attualità del vissuto e il tempo reale delle immagini: la solitudine degli intubati nelle rianimazioni, le bare in attesa di un vero riposo nelle chiese svuotate, l'affanno del personale sanitario, le città deserte. Tutto sotto lo sguardo allucinato del popolo italiano che, per la prima volta, avrà pensato che quelle storie, più che appartenere a connazionali malcapitati, rappresentavano un invito ad agire con estrema cautela, quando a circolare è il famigerato Covid-19.

Dopo l'incredulità e la sottovalutazione del rischio, abbiamo compreso di vivere un evento fuori dall'ordinario. E, come tutti i fatti straordinari che si rispettino, l'osservazione del loro divenire, per quanto scomposto, rappresenta l'elemento di razionalità che spinge a trovare soluzioni. Nell'immediato e per il futuro. Se questo elemento di spinta all'immaginazione di nuove architetture organizzative, atte a sviluppare una capacità di resilienza alle incognite legate allo sviluppo demografico e alle mutate condizioni ambientali sia in atto, in un tempo non lontano si vedrà.

## Informare e disciplinare: la comunicazione nell'emergenza

Nell'immediato, una crisi di così vaste proporzioni, che ha condotto alla morte decine di migliaia di cittadini italiani, ha posto il Governo nelle condizioni di agire necessariamente sul piano della conservazione della vita, adottando tutti quegli accorgimenti atti a ridurre drasticamente il numero delle persone liberamente circolanti, potenziali vittime della pandemia. In altri termini, come si dirà, in assenza di una cura ad una malattia letale e sconosciuta e di un piano d'intervento sanitario specificatamente pensato, si è posta l'urgenza di una massiva e penetrante campagna di disciplinamento, mai sperimentata prima, che doveva agire con velocità, abilità ed efficacia sui comportamenti di ciascuno, in modo trasversale ed orizzontale, senza distinzione di età, sesso, posizione sociale nell'obiettivo di interrompere la contagiosità. E senza andare troppo per il sottile in ordine alla qualità delle relazioni familiari che sarebbero state investite dai divieti imposti per ragioni di sicurezza e dei nuclei abitativi che, dai più accoglienti a quelli meno confortevoli, si sarebbero trasformati in residenze coatte, dalle quali uscire solo per motivate ragioni autocertificate.

La strategia di risposta all'emergenza internazionale dichiarata dall'OMS da parte del Governo comincia un po' in sordina e tra lo scetticismo generale, nonostante che il 31 gennaio del 2020 il Consiglio dei Ministri sarà costretto a dichiarare lo stato di emergenza e decretare, quasi due mesi dopo, il 9 marzo, il *lockdown*. Qualche settimana prima, il 5 febbraio, si procedette, nel quadro delle misure contro la pandemia, alla istituzione del Comitato tecnico scientifico, composto da esperti e qualificati rappresentanti degli Enti e dello Stato. Il Comitato ha il compito di supportare il Capo del Dipartimento della Protezione civile nelle attività finalizzate al superamento dell'emergenza epidemiologica da Covid-19, proponendo e valutando soluzioni, fornendo suggerimenti alla politica e nel porsi quale interfaccia con la opinione pubblica.

Paradossalmente, però, nel XXI secolo, l'unico rimedio possibile alla malattia e nello stesso tempo alla diffusione del virus resta quello somministrato agli infetti fin dal XIII secolo. Una metodica, quella del distanziamento sociale, in termini di efficacia, validata a livello scientifico da secoli di applicazione e che diventa, allo stato dei fatti, la soluzione panacea, il mantra con il quale persuadere gli italiani a rinunciare ad alcune libertà fondamentali e alla vita sociale per tutelare la vita. Sicuramente, le decisioni prese dal Governo si basano sul diritto di precauzione e sul bilanciamento tra diritti, facendo prevalere quello sulla salute.

D'altra parte, secondo quanto sostenuto dalla biopolitica post novecentesca il governo dei corpi è centrale al potere politico (si veda ad es. Agamben 1995) e «la questione della vita sembra accamparsi al centro dell'esperienza contemporanea come l'unica fonte di legittimazione indiscussa» (Esposito 2004).

L'atteggiamento poco convinto e desultorio di diversi Capi di Governo, rispetto all'ampiezza e alla pericolosità della pandemia nei primi giorni di gennaio, è stato --- sul fronte opposto --- un *refrain* piuttosto diffuso, così come diffusa è stata la sottovalutazione del rischio pandemico. Come dimenticare Boris Johnson e le sue teorie quasi eugenetiche che sembravano porre come un fatto scontato la perdita silenziosa di un numero impressionante di anziani, nella ineludibilità della situazione. Nelle uscite pubbliche del presidente americano, Donald Tramp, per il quale il virus esiste con l'obiettivo della destabilizzazione dell'economia globale, e, forse, del suo idillio con l'elettorato, permane il *leitmotiv* dubbioso ed irridente verso la scelta del pugno duro contro il Coronavirus.

Perfino il nostro Governo si è caratterizzato nelle prime ore dell'epidemia per un atteggiamento paternalistico e sufficiente: il premier Giuseppe Conte invitata a non creare panico, terrore e allarmismo, salvo poi, fatalmente, con la discesa in campo del Comitato tecnico scientifico, cambiare rotta totalmente, per sposare le linea del rigore assoluto.

In qualche modo si riscontrerà che il rigore delle scelte o l'atteggiamento derisorio dei Capi di Governo avrà influito sui comportamenti e la capacità dei cittadini di adeguarsi alle regole imposte. In altri termini è il nesso che controprova l'efficacia della strategia dell'emergenza.

## Le strategie governative di contrasto alle fake news

In ordine alle strategie di disciplinamento adottate dal Governo e dalle Istituzioni territoriali, è stato necessario avviare contestualmente un contrasto sistematico alle *fake news*, la cui pericolosità si aggravava parallelamente alla enfatizzazione, sprigionata dal generale senso di disorientamento della popolazione. Un rischio potenziale e ancor più reale da sterilizzare con energia per evitare che l'azione del Governo subisse inframmettenze distorsive, con malaugurate ricadute sui comportamenti individuali e sociali. L'incubo del falso e del contraffatto, ovvero le notizie che perdono la loro consistenza di veridicità ed assumono un altro tipo di finalità, è rilevato già ampiamente dal report di Eurobarometro (2018), non legato alla pandemia e, pur nonostante, rivelatore di un ben 71 per cento di cittadini europei imbattutisi in notizie alterate. Il forte timore delle organizzazioni governative verso le *fake,* a partire dall'Organizzazione mondiale della Sanità, è conseguente sia al loro potere di agire sull'emotività e sia al loro prolificare all'infinito.

L'Organizzazione mondiale della sanità ha adottato l'espressione *infodemic* (infodemia)[^tollis-1] per indicare l'epidemia da cattiva informazione, in questo caso legata al Coronavirus, con ciò rilevando una carenza di semplice informazione, magari anche motivata dalla esigenza dei cittadini di essere aiutati nella comprensione dei contesti legati ad un fenomeno pandemico, oltre che degli aspetti medico scientifici della malattia in sé.

[^tollis-1]: «Dall'ingl. *infodemic*, a sua volta composto dai s. info(rmation) ('informazione') ed (epi)demic ('epidemia'). Secondo quanto documentato da Licia Corbolante ... in inglese infodemic è una parola d'autore, coniata da David J. Rothkopf, il quale ne ha trattato in un articolo comparso nel quotidiano «Washington Post», When the Buzz Bites Back (11 maggio 2003)» (Vocabolario Treccani 2020; cfr. Rothkopf 2003)

Nel corso di queste settimane, sono state diverse le notizie che hanno ingenerato confusione e paure di varia intensità, anche a causa delle scarse conoscenze consolidate sul virus. Tra le *fake* che giocavano su tale confusione vale la pena ricordare l'asserita pericolosità dell'uso della mascherina, o quella relativa alla questione della contaminazione degli oggetti (puntualmente, le agenzie di stampa hanno battuto notizie di vari laboratori universitari testanti la resistenza del virus su alcuni materiali maggiormente utilizzati nella nostra quotidianità), o ancora l'ipotesi che il Covid-19 circolasse nell'aria, attivo anche su lunghe distanze.

In Abruzzo, una ulteriore *fake* ha riguardato, il giorno successivo al *lockdown*, il presunto "sbarco" di carri armati al casello autostradale di Città sant'Angelo che, secondo la vulgata, avrebbero dovuto accompagnare le misure del Governo di restrizione delle libertà personali. Timori di leggi marziali, come nel film "Attacco al potere", hanno dato fin da subito la misura del grado di condizionamento dei cittadini. Fortunatamente per gli italiani si trattava di carri diretti ad Aviano, per una esercitazione nell'ambito del programma di sicurezza *Defender Europe 20.*

Infine, la *fake* regina che tarda a morire e, anzi, rivive con una certa ciclicità, con il suo seguito di angosce e *mainstreaming* complottisti, è relativa alla genesi non biologica del virus fuoriuscito da un laboratorio di Wuhan.

In questo quadro fortemente preoccupante per tutte le Istituzioni, si colloca anche l'attenzione del Governo italiano a contrastare notizie e racconti che potrebbero turbare l'opinione pubblica e minare le misure di contenimento del contagio. Si concretizza così l'avvio di un'attività di *debunking,* grazie alla nascita dell'Unità di monitoraggio per il contrasto delle *fake* sul Covid-19.

Il contributo della task force è «supportare le istituzioni attraverso proposte, analisi e strumenti che facilitino la diffusione di informazioni scientificamente affidabili sull'emergenza sanitaria, nella convinzione che il miglior contrasto alla cattiva informazione sia la capacità di ciascun cittadino di saper trovare da sé le notizie e le risposte di cui ha bisogno». La task force governativa, dopo due mesi di attività ha diffuso un documento di 12 pagine contenente un programma operativo che individua tre aree d'intervento. La prima prevede di facilitare l'accesso dei cittadini alle comunicazioni ufficiali e ai contenuti scientificamente più attendibili; la seconda punta a fornire agli utenti strumenti che gli permettano di distinguere una fake news da una notizia attendibile; l'ultima consiste nel monitorare le informazioni online, individuando le notizie che circolano di più e quelle che diventano oggetto di dibattito pubblico: il tutto con l'obiettivo di orientare in maniera più efficace i messaggi provenienti dalle Istituzioni.

Con qualche tendenza all'eccesso dei toni, "*Scacco matto alle bufale*" è, invece, lo slogan scelto dal Ministero della Salute per identificare una rubrica settimanale, sul proprio sito istituzionale, dove raccogliere le principali *fake news*: «Disinformazione e fake news -- si spiega - sono pericolose sempre, tanto più quando riguardano temi di salute. In un momento di emergenza come quello che stiamo attraversando, il flusso di false informazioni, soprattutto in rete e sui social, è particolarmente massiccio e districarsi nel mare magnum di notizie che vengono diffuse non è facile, anche per i più esperti. La raccomandazione che il Ministero rivolge a tutti è quindi quella di affidarsi a fonti ufficiali e certificate per non cadere vittime di informazioni scorrette che alimentano ansia e comportamenti inadeguati». Le bufale vengono confutate dagli esperti del Ministero e dell'Istituto superiore di sanità. (Ministero della Salute, 2020).

## L'emergenza cambia la comunicazione d'emergenza. {#cap4-3}

La comunicazione d'emergenza ha le sue regole, esprimibili in cinque parole-chiave: interazione, credibilità ed autorevolezza, regia unica, semplicità dei messaggi e pacatezza. La sua applicazione durante la pandemia non è stata tecnicamente rigorosa, come rilevato da autorevoli osservatori. Certamente lo scenario si presentava drammatico e problematico sul piano degli strumenti normativi cui ricorrere per limitare le libertà dei cittadini. Solo il requisito dell'emergenza, dovendo rispondere velocemente agli accadimenti, poteva consentire azioni tempestive ed una velocizzazione delle procedure, e superare gli ostacoli burocratici per scuola, blocco dei voli e *smart working*.

Fatto si è che queste cinque regole non hanno avuto un riscontro nella prassi. Anzitutto, sulla base degli strumenti comunicativi utilizzati.

### Interazione

L'interazione che rappresenta un momento fondamentale di contatto con i cittadini, per cercare di raccogliere i loro turbamenti, tensioni e preoccupazioni e governarli, si è rivelato uno pseudo incontro. Infatti, tranne che per il lavoro svolto da alcuni social media istituzionali, dove si è visto il tentativo, soprattutto delle Regioni, di aprire un varco di ascolto individualizzato; nelle Pubbliche amministrazioni statali si è fatto gran uso di *frequently asked questions* (FAQ), ovvero le domande ricorrenti degli utenti alle quali si associa una lista con le risposte. Cosicché, a distanza di un mese dalla dichiarazione di emergenza i canali Facebook, Twitter, Instagram e YouTube del Ministero della Salute «risultavano ingaggiati solo sotto il profilo delle pubblicazioni ed informazioni e gli aggiornamenti ma le molte domande sono rimaste senza risposta, situazione decisamente anomala rispetto alle *best practice* in materia di comunicazione digitale» (Poma 2020, p. 12).

### Credibilità e autorevolezza {#credibilita}

Sul piano della credibilità e dell'autorevolezza, il Governo ha dovuto fare i conti con la portata dell'impetuoso, oscuro e mortale contagio della malattia. I due canoni, da una parte, sono riferibili a tutti i messaggi proveniente dal Governo rivolti all'opinione pubblica e, dall'altra, alla capacità del mondo scientifico di essere all'altezza delle enormi aspettative delle comunità di persone, che a tutt'oggi continuano ad intrattenere una visione ottocentesca dell'infallibilità della scienza,

Ben poco sappiamo ad oggi, invece, sulla natura del virus e le eventuali mutazioni, mentre le cure sono ancora sottoposte a sperimentazione. Altrettanto dicasi sui postumi che la malattia lascia sulla salute, anche tenuto conto che i farmaci utilizzati --- non specifici ma gli unici disponibili --- potrebbero aver creato ulteriori danni.

Credibilità ed autorevolezza della comunità scientifica sono state così travolte dal Covid-19 che si è abbattuto su tutti gli Stati del mondo, se pur in tempi e con intensità diversi. Si tenga sempre ben presente il dato della sottovalutazione iniziale dei diversi leader: una sottostima del pericolo che ha molto contato nella virulenta progressione del virus e sulla tardiva attenzione riservata, per esempio, alle protezioni individuali per i sanitari.

Secondo Poma (2020), «Anche il Collettivo Wu Ming non ha il minimo dubbio circa il fallimento comunicativo di scienziati ed «esperti» nei giorni del Covid-19: pareri discordanti in cui le voci di scienziati di vario titolo (medici, virologi, epidemiologi etc.) si sono mescolate e sovrapposte creando confusione e timori. Per la prima volta "gli scienziati si sono trovati improvvisamente al centro del palcoscenico" afferma Ming aggiungendo che "come sarebbe stato ragionevole attendersi, hanno mostrato un certo impaccio nel rapportarsi a contesti poco frequentati. Nemmeno i più sobri erano attrezzati a comprendere l'effetto che semplici constatazioni 'da laboratorio' possono avere all'interno di una comunità ben più ampia e magari attraversata dal terrore." La comunità scientifica ha preso la parola senza conoscere le dinamiche che caratterizzano i mass media "abituati a rivolgersi a comunità con cui in genere si condividono linguaggi impliciti ed espliciti" ed utilizzando una retorica che ha confuso, più che chiarire, il grande pubblico. La responsabilità di questa debacle sull'uso pubblico della scienza è attribuibile a precise categorie: giornalisti e scienziati» (p. 11).

### Regia unica

Il Governo, affiancato dal Comitato tecnico scientifico e, qualche volta, da questo bypassato ha fornito alla comunicazione politica, attraverso l'azione della Protezione civile, gli elementi razionali, metodologici e disciplinanti con i quali custodire e proteggere, oltre che le vite degli italiani, anche la propria azione politica. D'altra parte la narrazione da fornire alla complessità degli interessi in gioco, sociali ed economici anzitutto, era chiamata a prevenire eventuali fenomeni di rimbalzo legati ad orientamenti centrifughi e spinte segmentanti. Humus non congeniale al Governo, impegnato a costruire un adeguato cordone sanitario caratterizzantesi per pochi ma chiari obiettivi.

Non si è così lontani dai re taumaturghi (Bloch 1924) e dal loro potere di guarire i sudditi grazie alla natura "divina" della loro regalità. Effetto registrato dai sondaggi che evidenziano come i leader, perfino quelli che non si sono contraddistinti per un controllo immediato della situazione, godono di una nuova popolarità. In questo rapporto insolitamente figliale, i cittadini sembrano manifestare un bisogno atavico e per certi versi irrazionale, oggi come nel passato, di guardare al ruolo guida del capo con l'atteggiamento di chi chiede più protezione e sicurezza. Il politologo Mueller (1970), categorizzò questo fenomeno con l'espressione "*rally round the flag effect*", letteralmente l'effetto di stringersi attorno alla bandiera.

I Capi di Governo sono re taumaturgi ed in qualche modo se ne sentono investiti: si pensi al presidente Conte e alla sua solenne e simbolica solitudine, nella cornice austera nella quale viene collocato, nell'attesa ora degli aggiornamenti alla Nazione, a reti unificate. Un appuntamento serotino durante il quale si invoca lo spirito unitario e si sottolinea con forza l'importanza della salute degli italiani che non può essere barattata o piegata alle esigenze dei mercati e dell'economia e, neanche, del debito pubblico. Capi di Governo taumaturgi che non disdegnano neppure la foggia da generali che, per restare nella metafora di guerra che è stata sfruttata, spesso per drammatizzare in senso emotivo lo sconforto per un evento così improvviso ed immanente, conducono la cittadinanza a vincere la battaglia contro il Coronavirus, utilizzando poteri speciali.

### Semplicità e pacatezza {#semplicita}

In relazione, infine, agli altri due canoni della comunicazione d'emergenza, semplicità dei messaggi e pacatezza dei toni, si può dire che gli errori non sono mancati, soprattutto in relazione alle svariate ordinanze ed ai Dpcm: basti ricordare le autodichiarazioni che subivano modifiche ad ogni nuovo Decreto del Presidente del Consiglio dei Ministri, nonché alle sopra ricordate indicazioni sull'uso della mascherina.

## Trasparenza o "dittatura computazionale"?

La regia unica, architettata attorno ai due messaggi chiave, restate a casa e distanziatevi, si rivelerà il dispositivo fondamentale della strategia governativa di contenimento e riduzione del contagio.

In tale quadro, i dati hanno svolto un ruolo fondamentale nell'instaurare quella che io chiamo "dittatura computazionale", favorendo la definitiva accettazione sociale della segregazione. Conferenze stampa pomeridiane della Protezione civile, con altrettanti bollettini che rilevavano i morti e i ricoveri in terapia intensiva, hanno acquisito, in termini di importanza, lo status di *breaking news.* I dati che venivano forniti hanno avuto l'effetto dirompente di influenzare le aperture di tutti i mezzi di comunicazione: da quelli tradizionali ai social, tenuto conto che la "semantica" numerica è facilmente assorbibile dalle istanze della virtualità e che una delle regole di valutazione delle notizie è proprio quella del dato in sé, della dimensione valoriale ma anche emozionale che il numero o la percentuale riescono ad esprimere.

In definitiva, i dati costituiscono un elemento potentissimo di gerarchizzazione della notizia e la loro funzionalità, nel momento del disciplinamento, si intuisce nelle scelte compiute dal Governo: agire sulla coscienza collettiva attraverso la freddezza dei numeri e, soprattutto, dei numeri relativi ai deceduti e ai contagiati può amplificare la drammaticità della situazione. Non necessariamente, però, con un intento orientato a scenari di sospensione della democrazia, come nei timori di Paolo Mieli che interpellato sulla eventuale seconda ondata di Coronavirus, immagina una «svolta autoritaria quasi sicura» (*Atlantide*, 2020), ed invita, perciò, a comportarsi responsabilmente; quanto tuttalpiù per l'urgenza di agire per le vie di fatto, con tempismo e con la massima efficacia possibile.

Sui dati ci si dava appuntamento nel pomeriggio di ogni giorno con la Protezione civile, e di meri dati era composto il relativo comunicato stampa. Di soli dati si nutriva la mappa aggiornata quotidianamente ed ancora una proiezione di dati era quella che compariva sui grafici riferibili al totale dei positivi, dei guariti, dei deceduti e dei casi totali. Questa proposta comunicativa, orientata a corroborare la strategia del disciplinamento, suggestiona e avviluppa a tal punto da "contagiare" tutta la filiera della comunicazione sia in maniera orizzontale, tutti i media, e sia in maniera verticale, dal Governo alle Regioni, ai Comuni.

La conferma arriva anche dal posizionamento dell'opinione pubblica rispetto alla dittatura computazionale e la necessità di tenersi informati impatta anche sull'ascolto dei Tg, con un aumento del +29 per cento per i nazionali e del +42 per cento per quelli regionali. Nella giornata del 12 marzo, a due giorni dal *lockdown*, tutti i telegiornali dei principali broadcaster nazionali mostrano incrementi superiori al 50 percento. Alcuni palinsesti televisivi si riorganizzano aprendo finestre sull'argomento (Confindustria.it, 2020). Le dirette Facebook del Presidente del Consiglio fanno registrare in pochi giorni un picco di like che passa da 1,65 a 2,15 milioni.

La "dittatura computazionale" fa tornare di moda l'onnipresente passione per l'infodata. Vale l'esempio del *Sole 24 ore* che apre all'interno delle sue prestigiose pagine uno spazio dedicato al Covid nella rubrica intitolata "*Infodata: le notizie raccontate con i numeri"*.

Tra l'altro, è sintomatico, in questo raccontare, il continuo stabilire un nesso tra l'espressione numerica e i comportamenti individuali, con ciò ammettendo chiaramente che la lezione principale della "dittatura computazionale" è stata ben assorbita e, che, accanto a questa, è venuta germogliando l'idea che, paradossalmente, la responsabilità del contagio sia ormai tutta nelle mani degli italiani che, invece, si aspettavano di essere tutelati dal loro Paese.

Secondo Cazzola (2020), «l'aspetto più stupefacente della crisi da virus è la manipolazione dell'opinione pubblica che, per paura del mostro sconosciuto, ha accettato supinamente di cambiare vita, abitudini, prospettive professionali e comportamenti affettivi (...). Le direttive impartire dalle autorità sono diventate un dogma al punto di promuovere una sorta di "vigilanza civica"» (p. 26).

È dunque lecito chiedersi se è il principio di trasparenza quello che si è offerto con la "dittatura computazionale" o, piuttosto, uno strumento di standardizzazione dei comportamenti e di sedazione del giudizio.

La necessità di trasparenza viene esplicitamente richiamata dal capo della Protezione civile, Angelo Borrelli, nel momento in cui si manifesta scetticismo per la scelta di una comunicazione quotidiana, ad appuntamento fisso, in termini di bollettini impietosi sui morti e sui contagi. Ma è davvero di trasparenza che si tratta? Qual è l'eziologia di questi dati? I numeri sono certamente ufficiali ma non rispondenti alla verità, ha modo di spiegare il sindaco di Milano, Giuseppe Sala. Ciò che si contesta ai bollettini della Protezione civile è la poca omogeneità nella raccolta dei numeri e la pressoché sconosciuta consistenza delle persone contagiate. Tutto questo «non solo non ci fornisce un disegno veritiero dello stato dei contagi, ma nemmeno ci permette di mettere a punto una strategia adeguata per uscire dall'emergenza» (Ferraglioli 2020). Secondo le stime di esperti e virologi e della stessa Protezione civile i contagiati potrebbero essere dieci volte di più. Nell'articolo pubblicato sul Corriere della Sera intitolato *E se la statistica aiutasse i virologi?* (Di Vico 2020) si spiega, ad esempio, che due ex presidenti dell'Istat, insieme ad altri tre colleghi si sono fatti parte attiva verso il Ministro della Salute e il Presidente dell'Istituto superiore della sanità di una proposta basata sulla strategia del campione statistico. Per produrre dati rappresentativi bisogna realizzare «un protocollo di osservazione a campione», che comprenda duemila persone per Regione, alle quali effettuare il tampone in maniera sistematica e controllata, prendendo in considerazione i sintomatici e gli asintomatici.

## L'esperienza della Regione Abruzzo {#cap4-5}

L'insidiosissimo tema del mancato coordinamento tra le Istituzioni nazionali e quelle locali, è stato affrontato in termini polemici verso il Governo e ribadito anche da autorevoli giuristi come Sabino Cassese. Questi ha osservato la mancata applicazione dell'articolo 117 della Costituzione che riserva allo Stato i compiti in materia di profilassi internazionale; dell'articolo 120 della Costituzione che consente al Governo di sostituirsi alle Regioni, in caso di pericolo grave per l'incolumità, e della legge 833 del 1978 che assegna al Ministro della Salute il compito di intervenire in caso di epidemie. Un teatro politico è andato in scena tra Governo e Regioni per la preparazione della fase due, ovvero quella della graduale riapertura delle attività. Un argomento da strumentalizzare e congeniale ai Presidenti di Regioni, in deficit di visibilità, rispetto alla predominanza, anche in termini di consenso, del Premier taumaturgo. Sindrome che non ha risparmiato neppure i sindaci che hanno emesso ordinanze ripetitive di norme statali, perfino tautologiche e qualche volta con limitazioni più stringenti.

Pur in presenza di toni conflittuali è apparso chiaro che il disciplinamento, attuato anche grazie alla "dittatura computazionale", aveva già largamente esplicitato i suoi effetti, come mostra la comunicazione d'emergenza delle Regioni.

Questa risulta fagocitata dal rigido modello numerico della Protezione civile, come evidenzia, ad esempio, anche il caso di Regione Abruzzo, per la quale la comunicazione affidata ai dati resta l'unico contenuto informativo nella fase convulsa del picco della malattia.

Regione Abruzzo alle 15.15 di ogni pomeriggio emette il suo di "bollettino di guerra": un comunicato stampa accompagnato -- sempre sull'esempio della Protezione civile - da *dashboard* e grafici che indugiano all'uso della *data visualization,* anche con una certa ricerca estetica, come se non si trattasse di eventi tragici. Anche questo contribuisce a orientare il pensiero prevalentemente all'analisi di questi dati.

I bollettini emessi da Regione Abruzzo vengono accolti dalle contestazioni sui social, puntualmente registrate dal team social, dedicato a rispondere ai quesiti che ci pongono i cittadini, dando risposte vere a domande vere. Il processo di disintermediazione dei *new media* in questo caso però ci si è rivoltato contro, trovando proprio nei dati un facile appiglio per la conflittualità. Abbiamo anche rilevato la presenza di veri e propri agitatori, portatori di teorie del tutto personali, volte a screditare l'Istituzione, e motivo di preoccupazione e smarrimento sui social.

Interpretando questi fenomeni come reazione e protesta alla mancanza di informazione, sostituita dai dati nudi e crudi, la Regione Abruzzo ha risposto dando vita a uno strumento comunicativo nuovo, la rubrica "Sos Coronavirus. La Regione in emergenza" ([www.regione.abruzzo.it/content/sos-coronavirus-rubrica-della-regione-abruzzo-sullemergenza](https://www.regione.abruzzo.it/content/sos-coronavirus-rubrica-della-regione-abruzzo-sullemergenza){.uri}). Informare significa infatti dare i dati all'interno di una spiegazione più generale. In questo modo, i dati tornano ad assumere il loro ruolo fondamentale di riscontro, ma nell'ambito di una narrazione coerente ed integrata.

La rubrica è nata nel web e per il web, ed è stata interamente realizzata da remoto e si configura come una innovazione prodotta dallo *smart working* e frutto di un modello organizzativo che ha sfruttato i sistemi di video conferenza, attivati tramite dispositivi mobili, facendo della loro agilità e versatilità un punto di forza, assolutamente in linea con la cogenza degli eventi e le condizioni magmatiche della pandemia.

Giorno dopo giorno, dal 12 marzo, *Sos Coronavirus* ha raccontato la pandemia sul piano delle misure amministrative e anche su quello sanitario, accompagnando la comunicazione dei dati con interviste ai componenti del Gruppo tecnico scientifico regionale, individuato dalla Giunta regionale. Oltre a ciò, abbiamo vagliato le domande dell'utenza, rivolgendole poi a medici e amministratori regionali. La rubrica è stata quindi il punto di arrivo di una interazione reale con i cittadini, che hanno costruito il palinsesto.

Per gestire le situazioni conflittuali, abbiamo dunque scelto una comunicazione istituzionale rigorosa e assertiva da un lato, e dall'altro di interpretare le esigenze, le paure e i timori degli utenti, e dare loro risposta. Sono stati presentati con particolare attenzione quei contenuti che incidevano sulla quotidianità dei cittadini abruzzesi: il blocco di determinate cure ospedaliere e degli interventi chirurgici, la gestione degli sport, la ristorazione a domicilio, le misure economiche.

Tuttavia, è stato sul piano della informazione sanitaria che *Sos Coronavirus. La Regione in emergenza* ha dato il suo contributo più innovativo e significativo, accompagnando dashboard e dati con una lettura medico scientifica delle curve di contagio, dal monitoraggio dei posti letto e delle terapie intensive, alla strategia regionale per i tamponamenti, dai risultati delle cure sperimentali, dalle cure domiciliari, all'iter di anamnesi della malattia per evitare il peggioramento polmonare.

I pareri degli infettivologi hanno fatto registrare punte di 30.000 visualizzazioni su Facebook e i temi trattati sono stati usati in termini assertivi verso le posizioni conflittuali espresse attraverso i post. Evitare le polemiche, informare in modo imparziale e rigoroso, usare toni adeguati alla complessità del momento hanno favorito l'instaurarsi di un processo empatico tra Istituzione e cittadini ma anche tra l'Istituzione ed i media tradizionali.

L'appuntamento quotidiano, pubblicato sul portale regionale, e sui canali social (YouTube, Facebook, Instagram), è stato spesso ripreso da emittenti e quotidiani regionali, che quotidianamente utilizzano i nostri contenuti, proponendoli ai loro spettatori e lettori. In questo senso, i giornalisti della redazione social hanno ricostruito una specie di catena di comando della comunicazione, alternativa a quella del Governo e della Protezione Civile, offrendo argomenti e temi per informare e per ragionare.

Cita come:

Tollis A. (2020), L'informazione mancante, fra "fake" e dashboard. L'iniziativa della Regione Abruzzo. In A. Vardanega (a c. di), *Emergenza Covid-19. Nuove tecnologie e nuove forme di socialità*. Teramo. 2020.
