# Riferimenti bibliografici {.unnumbered}

Agamben, G. (1995). Homo sacer Il potere sovrano e la nuda vita. Torino, Einaudi.

Altheide, D. L. (1997). The News Media, the Problem Frame, and the Production of Fear. *The Sociological Quarterly*, *38*(4), 647--668.

Altheide, D. L. e Michalowski, R. S. (1999). Fear in the News. *Sociological Quarterly*, *40*(3), 475--503.

Antenore, M. e Splendore, S. (2017). *Data journalism: guida essenziale alle notizie fatte con i numeri*. Milano, Mondadori Università.

Associazione Ondata. (2020). \#OpenData sul coronavirus: È successo davvero, continuiamo così. 16 marzo. *onData.it*. <http://blog.ondata.it/opendata-sul-coronavirus-e-successo-davvero/>

Atlantide (2020). La profezia di Paolo Mieli: «In Italia c'è il rischio di svolta autoritaria», 6 maggio 2020. La7. <https://www.la7.it/atlantide/video/la-profezia-di-paolo-mieli-in-italia-ce-il-rischio-di-svolta-autoritaria-06-05-2020-323503>

Bloch, M. (2005). I re taumaturghi,(1924). Einaudi, Torino.

Bogardus, E. S. (1947). Measurement of Personal-Group Relations. *Sociometry*, *10*(4), 306--311. <https://doi.org/10/cqhkxg>

Rothkopf, D. J. (2003). When the Buzz Bites Back. *Washington Post*, *11*, B01. <https://www1.udel.edu/globalagenda/2004/student/readings/infodemic.html>

Carr N. (2010). *Internet ci rende stupidi? Come la rete sta cambiando il nostro cervello*. Roma: Raffaello Cortina Editore.

Cazzola, G. (2020). Virus e politica, evitiamo un nuovo 8 settembre, *Il Riformista*, 10 aprile. <https://www.ilriformista.it/virus-e-politica-evitiamo-un-nuovo-8-settembre-59415/>

Chaplin, C. (1936, febbraio 11). *Modern Times* [Comedy, Drama, Family, Romance]. Charles Chaplin Productions.

Clark, A., & Chalmers, D. (1998). The Extended Mind. *Analysis,* *58*(1), 7-19. <http://www.jstor.org/stable/3328150>

Confindustria.it (2020) Radio e Tv. Ascolti al tempo del Coronavirus, *Confindustria.it*, 20 marzo. <https://confindustriaradiotv.it/ascolti-radio-e-tv-al-tempo-del-coronavirus/>

De Cesco, A. (2015). Gli specialisti del Data Journalism? Giovani, italiani e freelance. *Piazza Digitale* di Corriere.it, 28 maggio. <https://piazzadigitale.corriere.it/2015/05/28/gli-specialisti-del-data-journalism-giovani-italiani-e-freelance/>

Di Vico, D. (2020) E se la statistica aiutasse i virologi? *Corriere della Sera*, 26 marzo. <https://www.corriere.it/opinioni/20_marzo_26/se-statistica-aiutasse-virologi-0bc1f966-6f95-11ea-b81d-2856ba22fce7.shtml>

Esposito, R. (2006). Biopolitica*,* *Enciclopedia italiana Treccani, VII Appendice*.

Eurobarometro (2018). Fake news and disinformation online (Flash Eurobarometer 464). <https://ec.europa.eu/commfrontoffice/publicopinion/index.cfm/survey/getsurveydetail/instruments/flash/surveyky/2183>

Ferraglioli, G. (2020). Coronavirus, i numeri fra trasparenza e caos: quanto è utile rendere pubblici i dati giorno per giorno? *Open*, 27 marzo. <https://www.open.online/2020/03/27/coronavirus-i-numeri-fra-trasparenza-e-caos-quanto-e-utile-rendere-pubblici-i-dati-giorno-per-giorno/>

Foucault, M. (1975). *Sorvegliare e punire. Nascita della prigione*. Torino, Einaudi.

Gariglio, L. (2017). L'autoetnografia nel campo etnografico. *Etnografia e ricerca qualitativa*, 3/2017. <https://doi.org/10/ghpcqz>

Goffman, E. (1956). Embarrassment and Social Organization. *American Journal of Sociology*, *62*(3), 264--271.

Goffman, E. (1972). *Encounters: Two studies in the sociology of interaction*. Penguin.

Goffman, E. (1983). The interaction order: American Sociological Association, 1982 presidential address. *American sociological review*, *48*(1), 1--17.

Goleman, D. (2015). *Intelligenza sociale ed emotiva. Nell'educazione e nel lavoro.* Edizioni Centro Studi Erickson.

Hạnh, T.N. (2009). *Answers from the heart : practical responses to life's burning questions*. Berkeley, Calif: Parallax Press.

Human Highway (2020). L'informazione ai tempi di Covid-19. *humanhighway.it*, 1 maggio. <https://www.humanhighway.it/media-adv/linformazione-ai-tempi-di-covid-19.html>

Istat. (2020). *Una stagione mancata: Impatto del Covid-19 sul turismo* (Statistiche Today). Istat. <https://www.istat.it/it/archivio/242017>

Jones, S. H. (2007). Autoethnography. In *The Blackwell Encyclopedia of Sociology*. American Cancer Society. <https://doi.org/10.1002/9781405165518.wbeosa082>

Kabat-Zinn, J. (2011). *Dovunque tu vada ci sei già : capire la ricchezza del nostro presente per iniziare il cammino verso la consapevolezza*. Milano: Corbaccio.

Kabat-Zinn, J. (2016). *Vivere momento per momento : come usare la saggezza del corpo e della mente per sconfiggere lo stress, il dolore, l'ansia e la malattia*. Milano: Corbaccio.

Lebaron, F. (2020). Covid-19. L'anomie pandémique. *Savoir/Agir*, *N° 52*(2), 7--9.

Lipperini, L. (2018). *Parole ostili. 10 racconti* (2 edizione). Laterza.

Ludovisi, D. (2016). *Il potere dei dati. Il data journalism e le nuove frontiere del comunicare*. Firenze, Effequ.

Kenrick, D. T., & Griskevicius, V. (2013). The rational animal: how evolution made us smarter than we think. New York: Basic Books.

Kubrick, S. (1968, aprile 11). *2001: A Space Odyssey* [Adventure, Sci-Fi]. Metro-Goldwyn-Mayer (MGM),  Stanley Kubrick Productions.

Madeddu, D. (2020). *Allarme Sardegna, in tre mesi da 5 a 80 focolai. Ed è rissa tra i sindaci e l'assessore leghista sulla gestione dell'emergenza*. Il Sole 24 ORE (1 ottobre 2020). <https://www.ilsole24ore.com/art/allarme-sardegna-tre-mesi-5-80-focolai-ed-e-rissa-i-sindaci-e-l-assessore-leghista-gestione-dell-emergenza-ADbClrs>

Matera, V. (2020). Il coronavirus come fatto sociale totale: L'impatto culturale dell'epidemia. *ParliamoneOra*. 24 marzo. <http://www.parliamoneora.it/2020/03/24/il-coronavirus-come-fatto-sociale-totale-limpatto-culturale-dellepidemia/>

Mauss, M. (2016). *Saggio sul dono*. Giulio Einaudi Editore.

Meyer, P. (2001). *The New Precision Journalism*. Rowman & Littlefield Publishers.

Ministero della Salute (2020), Covid-19, scacco matto alle bufale. <https://www.salute.gov.it/portale/malattieInfettive/dettaglioNotizieMalattieInfettive.jsp?lingua=italiano&menu=notizie&p=dalministero&id=4327>

Morozov, E. (2014). *Internet non salverà il mondo : perchè non dobbiamo credere a chi pensa che la Rete possa risolvere ogni problema*. Milano: Mondadori.

Morozov, E. (2020, aprile 13). L'emergenza sanitaria e il rischio del totalitarismo. *Internazionale*. <https://www.internazionale.it/opinione/evgeny-morozov/2020/04/13/emergenza-sanitaria-totalitarismo>

Mueller, J. E. (1970). Presidential popularity from Truman to Johnson. *The American Political Science Review*, *64*(1), 18-34.

Poma, L. (2020), Governo Conte e Coronavirus. Analisi sulle frequenze della paura, *Formiche*, 27 marzo. <https://formiche.net/2020/03/governo-conte-coronavirus-paura/>

QuiFinanza (2020). Coronavirus, da Covid-free a focolaio: Scoppia il caso Sardegna. (22 agosto 2020). *QuiFinanza*. <https://quifinanza.it/info-utili/video/coronavirus-covid-free-focolaio-scoppia-caso-sardegna-solinas-lazio/409519/>

Romania, V. (2020). Interactional Anomie? Imaging Social Distance after COVID-19: A Goffmanian Perspective. *Sociologica*, *14*(1), 51--66. <https://doi.org/10/ghmw9v>

Saporiti, R. (2020). Open Data, arriva la mappa della Protezione Civile sui dati del contagio di Coronavirus in Italia. 9 marzo 2020. *Info Data - Il Sole 24 Ore*. <https://www.infodata.ilsole24ore.com/2020/03/09/open-data-arriva-la-mappa-della-protezione-civile-del-contagio-di-coronavirus-in-italia/>

Sennett, R. (2017). *L'uomo artigiano* (A. Bottini, Trad.). Feltrinelli.

Sennett, R. (2018). *Costruire e abitare: Etica per la città* (C. Spinoglio, Trad.). Feltrinelli.

Sky TG24. (2020). Come leggere i dati della Protezione Civile sul Coronavirus. 26 marzo 2020, *Sky TG24*. <https://tg24.sky.it/cronaca/2020/03/26/dati-protezione-civile-coronavirus.html>

Soderbergh, S. (2011, settembre 8). *Contagion* [Drama, Thriller]. Warner Bros.,  Participant,  Imagenation Abu Dhabi FZ.

Subioli, P. (2015). *Zen in the city: L'arte di fermarsi in un mondo che corre*. Roma: Edizioni Mediterranee.

Subioli, P. (2018). *Ama il tuo smartphone come te stesso*. Milano: Edizioni Red.

Tauberer, J. (2014). Open Government Data: The book. Joshua Tauberer.

Treccani. (s.d.). Crisi. In *Vocabolario on line*. Recuperato 9 dicembre 2020, da <https://www.treccani.it/vocabolario/crisi>

Tyldum, M. (2014, novembre 14). *The Imitation Game* [Biography, Drama, Thriller, War]. Black Bear Pictures,  FilmNation Entertainment,  Bristol Automotive.

Vardanega, A. (2020.a). L'imperatore è nudo (e noi passiamo le giornate in pigiama a leggere dat)i. Rivelazioni da un'apocalisse. In A. Guigoni & R. Ferrari (A c. Di), *Pandemia 2020. La vita in Italia con il Covid-19* (pagg. 76--82). M&J.

Vardanega, A. (2020.b). *L'incerta stagione* [presentazione]. Turismo e Covid-19, Unicollege SSML, Mantova. <https://www.slideshare.net/agnesevardanega/lincerta-stagione>

Vocabolario Treccani (2020). voce "Infodemia", *Neologismi 2020*. [https://www.treccani.it/vocabolario/infodemia\_(Neologismi)/](https://www.treccani.it/vocabolario/infodemia_(Neologismi)/){.uri}

Zunino, C. (2020). Borrelli: «I numeri sono altri. L'epidemia va più veloce della nostra burocrazia». 23 marzo 2020, *La Repubblica*. <https://rep.repubblica.it/pwa/generale/2020/03/23/news/coronavirus_borrelli_i_numeri_sono_altri_l_epidemia_va_piu_veloce_della_nostra_burocrazia_-252124440/>
